### ISSUE TITLE
多个app同时打开时报端口错误、打不开pdf资源

### ISSUE THREAD

**Issue by dingdedou** [aiyakuaile/pdf_js_viewer#2]
I/chromium( 3561): [INFO:CONSOLE(392)] "Uncaught SyntaxError: Unexpected token .", source: http://127.0.0.1:31211/pdfjs/build/pdf.js (392)
I/chromium( 3561): [INFO:CONSOLE(342)] "Uncaught SyntaxError: Unexpected token .", source: http://127.0.0.1:31211/pdfjs/web/viewer.js (342)

**Comment by aiyakuaile** [comment]
@dingdedou v1.0.5已经解决，您可以尝试一下
