### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by CeRBeR666** [aiyakuaile/pdf_js_viewer#3]
When i try your plugin give me like this error 
<img width="1096" alt="Ekran Resmi 2023-10-10 13 35 59" src="https://github.com/aiyakuaile/pdf_js_viewer/assets/504973/559da429-ebb2-41b0-b43f-dd7714f1ec1a">

**Comment by aiyakuaile** [comment]
@CeRBeR666    You should configure the usage permissions for HTTP，AndroidManifest.xml
```
<application
        android:usesCleartextTraffic="true"
        ......
```
or

```
<application
        android:networkSecurityConfig="@xml/network_security_config"
        ......
```

At the same time, internet permissions need to be configured

`<uses-permission android:name="android.permission.INTERNET" />`

**Comment by CeRBeR666** [comment]
Thank you for reply. 
You should also add this section to the install notes.
